### PR TITLE
fix platform libary conflict & added mining and axing

### PR DESCRIPTION
**Pull request by lmaodick1239**
I tried adding auto mining support (no afk tho)

### CODE REVIEW

**Comment by lmaodick1239** [comment]
ok so there are some things missing and redundant I'll add and remove them later

**Comment by lmaodick1239** [comment]
ok its not 100% but for not it works

**Comment by ExWaltz** [comment]
So far, it looks good. Ill do some tests and merge it afterwards.

**Comment by nopeAnon** [comment]
Ok, It works fine. I'll just update the requirements.txt. Thank you for your contribution!

**Comment by lmaodick1239** [comment]
im gonna be honese the import PIL line is unneeded i forgot to remove it before pushing im so sorry

edit nvm you guys fixed it

**Pull request merged**
