### PR TITLE
log fishing count + fixing the problem with exiting fishing mode

### PR DESCRIPTION
**Pull request by rastorguevia**
For some reason, when working, there are periodic problems with exiting fishing mode. The character is just standing near the lake. An example of the work of the correction is attached below. The computer is not weak and not loaded, so that's not the point.
[log.txt](https://github.com/nopeAnon/Automated-HoloCure-Fishing/files/12423995/log.txt)

Also added counter + development environment corrected inaccuracies.

### CODE REVIEW

**Comment by nopeAnon** [comment]
Thank you for the fix!

**Comment by Hexus-One** [comment]
Which linter/formatter are you using for development? I've been using VS Code + [Black](https://github.com/psf/black) which might explain the nuances with spacing and the clash with PyCharm IDE's linter 😅

The reason for `BASE_ROI` being spelled in uppercase is because it's effectively a constant - probably the better fix for readability would be to move it from function-level to module-level and keep the capitalisation.

The fix for exiting fishing mode may have unexpected behaviour - if the player chooses to manually exit fishing mode and do something else, the program will send an `enter` keypress every 30 seconds. Maybe a better solution would be to increase the delay between the two `enter` keypresses, or spam `enter` multiple times just to be sure 😆

**Comment by nopeAnon** [comment]
You're right on the capitalization. 
The bug usually happens around 20-40 fishing combo on my side. I think adding a delay after the second enter should fix it. Since, we have encountered a similar bug before https://github.com/nopeAnon/Automated-HoloCure-Fishing/issues/5#issuecomment-1685201961 I'll be testing it out and see how it goes

>spam `enter` multiple times

It might cancel the fishing out with the spam

**Comment by nopeAnon** [comment]
Changing the sleep to 0.2 and adding another sleep fixed it.

**Comment by Hexus-One** [comment]
> Changing the sleep to 0.2 and adding another sleep fixed it.

Ah nice I'm glad that worked :)

> > spam `enter` multiple times
> 
> It might cancel the fishing out with the spam

I tested just now - pressing `enter` multiple times while waiting for fish does nothing extra, only pressing the escape/cancel key will exit it. If you're really pressed to min-max everything then you could spam enter instead of increasing the delay but the difference made is on the order of like 20 mins saved every 16 hours [(I've been streaming the fishing bot running non-stop)](https://www.twitch.tv/videos/1906379247).

**Comment by rastorguevia** [comment]
> Which linter/formatter are you using for development? I've been using VS Code + [Black](https://github.com/psf/black) which might explain the nuances with spacing and the clash with PyCharm IDE's linter 😅


PyCharm )

**Comment by rastorguevia** [comment]
> Changing the sleep to 0.2 and adding another sleep fixed it.

No, its not
I just tested it
image

**Comment by nopeAnon** [comment]
Huh, weird. It is currently working on mine. Did you implement it like this?
 ```py
if min_val < 60_000_000:
    press(win, "enter")
    time.sleep(0.2)
    press(win, "enter")
    time.sleep(0.2)
```

image

**Comment by rastorguevia** [comment]
> Huh, weird. It is currently working on mine. Did you implement it like this?

I just update your rep ) 
So yes 
but this problem can manifest itself, as you saw in my log, both after 10 fishing and after 150

**Comment by nopeAnon** [comment]
ok I'll try the spam method for now and see if it works

**Comment by nopeAnon** [comment]
Spam works. Switching to spam method for now. Can you tell me if it works on your side?
image

**Comment by rastorguevia** [comment]
> Spam works. Switching to spam method for now. Can you tell me if it works on your side? 

Yeah, now we're cooking 
I test it for a while, and it works great 
image

**Pull request merged**
